version: '3.1'

services:
  generator:
    image: my-registry:55000/gen:ci-${}

  mail:
    image: mailhog/mailhog

  integrationtest:
    image: my-registry:55000/gen:integration-${BUILD_NUMBER}
    build: .